# Generated by Django 2.0 on 2017-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quincena', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('neto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
    ]
